name: Run Daily Script

on:
  schedule:
    - cron: '0 7 * * *'  # This means the script will run every day at 7:00 AM UTC (midnight Phoenix time)
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  run_script:
    runs-on: ubuntu-latest  # Choose the OS you want to use (ubuntu-latest is a common choice)

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python (you can choose the version you need)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can change this to the version you need

    # Step 3: Install dependencies (if you have any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Only if you have a requirements.txt file

    # Step 4: Run your Python script
    - name: Run daily script
      run: |
        python dailies.py  # Replace with the name of your Python script
